// <auto-generated />
using System;
using InfraEstrutura.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraEstrutura.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("CATEGORIA_ATIVO");

                    b.Property<bool>("ControlaEstoque")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("CATEGORIA_CONTROLA_ESTOQUE");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CATEGORIA_DATA_CRIACAO");

                    b.Property<int>("MaximoItens")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_MAXIMO_ITENS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CATEGORIA_NOME");

                    b.HasKey("Id");

                    b.ToTable("TB_CATEGORIA");
                });

            modelBuilder.Entity("Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PRODUTO_ATIVO");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUTO_CATEGORIA");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PRODUTO_DATA_CRIAÇÃO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRODUTO_NOME");

                    b.Property<decimal>("QuantidadeDisponivel")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PRODUTO_QUANTIDADE");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
